version: 2
jobs:
  build:
    docker:
      - image: docker:stable
    steps:
      - checkout

      - setup_remote_docker:
          docker_layer_caching: true

      - run:
          name: Build and test V1 Gazette
          command: docker build . --file build/Dockerfile.gazette-build --tag gazette-build

      - run:
          name: Build the V1 binary image
          command: docker build . --file build/cmd/Dockerfile.gazette

      - run:
          name: Build V1 stream-sum example
          command: docker build . --file build/examples/Dockerfile.stream-sum

      - run:
          name: Build and test V2 Gazette
          command: docker build ./v2/ --file v2/build/Dockerfile.gazette-build --tag gazette-build

      - run:
          name: Build the V2 binary image
          command: docker build ./v2/ --file v2/build/cmd/Dockerfile.gazette

      - run:
          name: Build V2 stream-sum example
          command: docker build ./v2/ --file v2/build/examples/Dockerfile.stream-sum
