# Default values for stream-sum.
# This is a YAML-formatted file.

consumer:
  replicaCount: 3
  nameOverride: stream-sum
  image:
    repository: liveramp/gazette-example-stream-sum
    module: /go/bin/summer.so

chunker:
  numJobs: 10
  numStreams: 1000
  chunksPerStream: 100
