apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "consumer.fullname" . }}
  labels:
    app.kubernetes.io/name: {{ include "consumer.name" . }}
    helm.sh/chart: {{ include "consumer.chart" . }}
    app.kubernetes.io/instance: {{ .Release.Name }}
    app.kubernetes.io/managed-by: {{ .Release.Service }}
    {{- if .Values.extraLabels }}
{{ toYaml .Values.extraLabels | indent 4 }}
    {{- end }}
data:
  gazette.ini: |
{{ tpl .Values.configIniTemplate . | indent 4 }}
