apiVersion: v1
appVersion: 2.0.0
description: Durable, distributed transaction logs for building streaming platforms.
name: gazette
version: 2.0.0
home: https://github.com/LiveRamp/gazette
sources:
  - https://github.com/LiveRamp/gazette
maintainers:
  - name: Johnny Graettinger
    email: johnny.graettinger@liveramp.com
  - name: Rupert Chen
    email: rupert.chen@liveramp.com
